version: "3.10"


x-postgres-environment: &x-postgres-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_DATABASE: ${POSTGRES_DATABASE}

services:
  backend:
    build: backend
    volumes:
      - "./backend/app:/application"
    environment:
      <<: [*x-postgres-environment]
      TG_TOKEN: ${TG_TOKEN}
    command: python main.py
    ports:
      - "8090:8090"

  database:
    restart: on-failure
    image: postgres:alpine
    environment:
      <<: [ *x-postgres-environment ]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
